In [1]:
#Instalando a biblioteca Dataset
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (0.1.2)

In [2]:
# Carrega o dataset de tweets em português do Hugging Face
from datasets import load_dataset

dataset = load_dataset("miguelribeirokk/crime_tweets_in_portuguese")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

61K_crime_tweets_portuguese.csv:   0%|          | 0.00/10.3M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/61715 [00:00<?, ? examples/s]

In [3]:
# Converte o dataset em um DataFrame (tabela) e mostra as primeiras linhas
import pandas as pd

df = pd.DataFrame(dataset['train'])
df.head()

,id,text,INSULT,IDENTITY_ATTACK,SEVERE_TOXICITY,THREAT,PROFANITY,TOXICITY,POSITIVE,NEUTRAL,...,ASSALTO,ROUBO,FURTO,ASSEDIO,SPUBLICA,HOMICIDIO,OUTRO,CRIME,KEYWORD,LOCAL
0,1,gatilho c a praca sete amg so os assaltos,0.0250,0.0188,0.0153,0.2921,0.0640,0.2381,0.0533,0.3576,...,1,0,0,0,0,0,0,1,1,0
1,2,na rodoviaria de sp nao aguardem proximo ao po...,0.0302,0.0041,0.0018,0.0062,0.0829,0.0590,0.0133,0.0237,...,0,0,0,0,1,0,0,1,1,1
2,3,eu espero que a policia esteja treinada para i...,0.0261,0.0188,0.0017,0.0070,0.0111,0.0476,0.1297,0.6832,...,0,0,0,0,1,0,0,1,1,1
3,4,assaltaram duas casas aqui na minha rua e agor...,0.0235,0.0224,0.0130,0.2567,0.0781,0.2396,0.0152,0.0867,...,1,0,0,0,0,0,0,1,1,0
4,5,sim e importante a apuracao para mostrar que f...,0.0363,0.0060,0.0041,0.0232,0.0173,0.0895,0.0819,0.4034,...,0,0,0,0,1,0,0,1,1,0

In [4]:
# Seleciona a coluna de texto (tweets), renomeia para "documento",
df_documentos = df[['text']].copy()

df_documentos.columns = ['documento']
df_documentos.insert(0, 'id', range(1, len(df_documentos) + 1))

df_documentos = df_documentos.head(50)

df_documentos.head()

   id                                          documento
0   1          gatilho c a praca sete amg so os assaltos
1   2  na rodoviaria de sp nao aguardem proximo ao po...
2   3  eu espero que a policia esteja treinada para i...
3   4  assaltaram duas casas aqui na minha rua e agor...
4   5  sim e importante a apuracao para mostrar que f...

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
df_documentos.to_csv('/content/documentos.csv',
                     index=False,
                     encoding='utf-8',
                     sep=';')

In [7]:
# Lista os arquivos que estão na pasta /content do Colab
import os
os.listdir('/content')

['.config', 'documentos.csv', 'drive', 'sample_data']

In [8]:
df_documentos = df[['text']].copy()

df_documentos.columns = ['documento']
df_documentos.insert(0, 'id', range(1, len(df_documentos) + 1))

df_documentos = df_documentos.head(50)

df_documentos.to_csv('/content/drive/MyDrive/Colab Notebooks/SRI/data/documentos.csv',
                     index=False,
                     encoding='utf-8',
                     sep=';')

In [9]:
df_teste = pd.read_csv('/content/documentos.csv', sep=';')
df_teste.shape

(50, 2)

In [10]:
with open('/content/drive/MyDrive/Colab Notebooks/SRI/data/documentos.csv', 'r', encoding='utf-8') as f:
    for i in range(3):
        print(f.readline())

id;documento

1;gatilho c a praca sete amg so os assaltos

2;na rodoviaria de sp nao aguardem proximo ao portao de embarque quase fui assaltada em marco pq n tinha essa maldade inves de ficar na praca de alimentacao la nao tem controle de quem vai embarcar ou nao so vao para o acesso de embarque uns 15 min que ja tera fila